name: Generate Keystore
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: keytool -genkey -v -keystore my-upload-key.jks -storepass MyStrongPass123 -alias upload -keypass MyStrongPass123 -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=FuturePath,O=FuturePath,C=US"
      - name: Encode to base64
        run: base64 -w 0 my-upload-key.jks > keystore-base64.txt
      - uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            my-upload-key.jks
            keystore-base64.txt
